var Struct = require('awestruct')
  , float = Struct.types.float

module.exports = Struct({
  resources: Struct({
    food: float
  , wood: float
  , stone: float
  , gold: float
  })
, headroom: float
, u0: float
, current_age: float
, num_relics: float
, u1: float
, u2: float
, u3: float
, pop_current: float
, u4: float
, u5: float
, u6: float
, u7: float
, u8: float
, u9: float
, u10: float
, total_units_created: float
, num_kills: float
, num_items_researched: float
, percent_map_explored: float
, u11: float
, u12: float
, u13: float
, u14: float
, u15: float
, u16: float
, u17: float
, u18: float
, u19: float
, pop_max: float
, u20: float
, u21: float
, u22: float
, farm_food_amount: float
, civilian_pop: float
, u23: float
, u24: float
, military_pop: float
, u25: float
, num_wonders: float
, u26: float
, u27: float
, u28: float
, u29: float
, u30: float
, u31: float
, total_gold_gathered: float
, u32: float
, u33: float
, u34: float
, total_resources_tributed: float
, u35: float
, u36: float
, u37: float
, u38: float
, u39: float
, u40: float
, u41: float
, u42: float
, u43: float
, u44: float
, u45: float
, u46: float
, u47: float
, u48: float
, u49: float
, total_team_kills: float
, u50: float
, u51: float
, u52: float
, u53: float
, u54: float
, u55: float
, u56: float
, u57: float
, u58: float
, u59: float
, num_units_queued: float
, num_units_making: float
, u60: float
, u61: float
, u62: float
, u63: float
, u64: float
, u65: float
, u66: float
, u67: float
, u68: float
, food_bonus: float
, wood_bonus: float
, stone_bonus: float
, gold_bonus: float
, u69: float
, u70: float
, u71: float
, total_civ_worth: float
, total_food_spent_on_upgrades: float
, u72: float
, total_trading_gold: float
, p1_tributed_to: float
, p2_tributed_to: float
, p3_tributed_to: float
, p4_tributed_to: float
, p5_tributed_to: float
, p6_tributed_to: float
, p7_tributed_to: float
, p8_tributed_to: float
, p1_unit_kill_worth: float
, p2_unit_kill_worth: float
, p3_unit_kill_worth: float
, p4_unit_kill_worth: float
, p5_unit_kill_worth: float
, p6_unit_kill_worth: float
, p7_unit_kill_worth: float
, p8_unit_kill_worth: float
, p1_num_razes: float
, p2_num_razes: float
, p3_num_razes: float
, p4_num_razes: float
, p5_num_razes: float
, p6_num_razes: float
, p7_num_razes: float
, p8_num_razes: float
, p1_raze_worth: float
, p2_raze_worth: float
, p3_raze_worth: float
, p4_raze_worth: float
, p5_raze_worth: float
, p6_raze_worth: float
, p7_raze_worth: float
, p8_raze_worth: float
, num_castles: float
, u73: float
, u74: float
, u75: float
, u76: float
, u77: float
, u78: float
, u79: float
, u80: float
, u81: float
, u82: float
, u83: float
, u84: float
, u85: float
, u86: float
, u87: float
, u88: float
, u89: float
, u90: float
, u91: float
, u92: float
, u93: float
, p1_tribute_recvd: float
, p2_tribute_recvd: float
, p3_tribute_recvd: float
, p4_tribute_recvd: float
, p5_tribute_recvd: float
, p6_tribute_recvd: float
, p7_tribute_recvd: float
, p8_tribute_recvd: float
, current_unit_worth: float
, current_building_worth: float
, total_food_gathered: float
, total_wood_gathered: float
, total_stone_gathered: float
, total_gold_gathered: float
, total_kill_and_raze_worth: float
, total_tribute_recvd: float
, u94: float
, castle_high: float
, wonder_high: float
, total_tribute_sent: float
, u95: float
, u96: float
, u97: float
, u98: float
, u99: float
, u100: float
, u101: float
, u102: float
, total_stone_castle_wonder: float
, u103: float
, u104: float
, u105: float
, u106: float
, u107: float
, u108: float
, u109: float
, u110: float
, u111: float
, u112: float
, u113: float
, u114: float
, u115: float
})
